name: Check Foundry Version

on:
  push:
    branches:
      - main

jobs:
  check_foundry_version:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up Foundry
        uses: foundry-rs/foundry-toolchain@v1
        
      - name: Run Foundry --version
        run: foundry --version
