name: Test Contract

on:
  push:
    branches:
      - main

jobs:
  test_contract:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up Foundry
        uses: foundry-rs/foundry-toolchain@v1
      
      - name: Run Contract Tests
        run: foundry test --verbose
